name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86,x86_64, aarch64]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU (for ARM emulation on x86)
      if: matrix.architecture == 'x86'
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Docker image
      run: |
        docker build -t moseiik --file Dockerfile .

    - name: Run Docker image and execute tests
      run: |
        docker run --rm my_docker_image
